### ISSUE TITLE
ConversationModel panic on large input (with 3-4 lines of text)

### ISSUE THREAD

**Issue by Qeenon** [guillaume-be/rust-bert#153]
thread 'tokio-runtime-worker' panicked at 'called Result::unwrap() on an Err value: Torch("index out of range in self\nException raised from operator() at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:677 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f634c696b29 in Amadeus/target/release/build/torch-sys-8dc810d88f246fa1/out/libtorch/libtorch/lib/libc10.so)\nframe #1: <unknown function> + 0xc12390 (0x7f634d4e5390 in Amadeus/target/release/build/torch-sys-8dc810d88f246fa1/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #2: <unknown function> + 0x10e5d4a (0x7f634d9b8d4a in Amadeus/target/release/build/torch-sys-8dc810d88f246fa1/out/libtorch/libtorch/lib/libtorch_cpu.so)\nframe #3: <unknown function> + 0x1b766 (0x7f634c61e766 in gcc/x86_64-pc-linux-gnu/11.1.0/libgomp.so.1)\nframe #4: <unknown function> + 0x7e3e (0x7f634a1d5e3e in /lib64/libpthread.so.0)\nframe #5: clone + 0x3f (0x7f6349fd173f in libc.so.6)\n")', .cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.4.1/src/wrappers/tensor_generated.rs:3649:87

**Comment by guillaume-be** [comment]
Hello @Qeenon ,

I believe I was able to reproduce the issue. When the user input to the conversation model is very large (1000 input tokens or more), the pipeline was not effective at truncating the length, leading to index error for the position embeddings (limited at 1024 position for DialoGPT models).

I have pushed a fix to the [conversation_model_fix](https://github.com/guillaume-be/rust-bert/tree/conversation_model_fox) branch. Could you please try it and let me know if this solves your issue?
```toml
[dependencies]
rust-bert = { git = "https://https://github.com/guillaume-be/rust-bert", branch = "conversation_model_fox" }
```

I am unsure as ~1000 tokens is significantly larger than 3-4 lines of text (more like 3 entire paragraphs). if this solves the issue I'd push a fix and release a patch version.

**Comment by Qeenon** [comment]
@guillaume-be no problem, thank you, will try to test

**Comment by Qeenon** [comment]
@guillaume-be sorry but had exactly same exception with this branch :(

but maybe it's translation model, will try to re-check to ensure what exactly fails tomorrow

**Comment by guillaume-be** [comment]
Thank you - it would be great if you could post a full stack trace (it is unclear where the index out of range happens) and an example to reproduce the error on my end).

**Comment by Qeenon** [comment]
@guillaume-be yes I was with translation, there backtrace

```
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_none_failed
   3: core::result::Result<T,E>::unwrap
             at /usr/lib/rust/1.52.1/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: tch::wrappers::tensor_generated::<impl tch::wrappers::tensor::Tensor>::embedding
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.4.1/src/wrappers/tensor_generated.rs:3649:9
   5: <tch::nn::sparse::Embedding as tch::nn::module::Module>::forward
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.4.1/src/nn/sparse.rs:53:9
   6: tch::nn::module::<impl tch::wrappers::tensor::Tensor>::apply
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.4.1/src/nn/module.rs:49:9
   7: rust_bert::bart::embeddings::SinusoidalPositionalEmbedding::forward
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/bart/embeddings.rs:116:9
   8: rust_bert::bart::embeddings::EmbeddingOption::forward
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/bart/embeddings.rs:34:17
   9: rust_bert::bart::encoder::BartEncoder::forward_t
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/bart/encoder.rs:214:30
  10: rust_bert::marian::marian_model::MarianForConditionalGeneration::encode
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/marian/marian_model.rs:626:9
  11: <rust_bert::marian::marian_model::MarianGenerator as rust_bert::pipelines::generation_utils::private_generation_utils::PrivateLanguageGenerator<rust_bert::marian::marian_model::MarianForConditionalGeneration,rust_tokenizers::vocab::marian_vocab::MarianVocab,rust_tokenizers::tokenizer::marian_tokenizer::MarianTokenizer>>::encode
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/marian/marian_model.rs:906:14
  12: rust_bert::pipelines::generation_utils::LanguageGenerator::generate_from_ids_and_past
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/pipelines/generation_utils.rs:1376:35
  13: rust_bert::pipelines::generation_utils::LanguageGenerator::generate_indices
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/pipelines/generation_utils.rs:1311:9
  14: rust_bert::pipelines::generation_utils::LanguageGenerator::generate
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/pipelines/generation_utils.rs:1209:25
  15: rust_bert::pipelines::translation::TranslationOption::generate
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/pipelines/translation.rs:678:17
  16: rust_bert::pipelines::translation::TranslationModel::translate
             at /root/.cargo/git/checkouts/rust-bert-89c9227f9795e25f/002b3c1/src/pipelines/translation.rs:761:21
  17: amadeus::steins::ai::bert::bert_tests::chat_big_text_test
             at ./src/steins/ai/bert.rs:272:16
  18: amadeus::steins::ai::bert::bert_tests::chat_big_text_test::{{closure}}
             at ./src/steins/ai/bert.rs:252:3
  19: core::ops::function::FnOnce::call_once
             at /usr/lib/rust/1.52.1/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Qeenon** [comment]
there test
```rust
#[cfg(test)]
mod bert_tests {
  use super::*;
  #[test]
  fn chat_big_text_test() {
    let conversation_model = ConversationModel::new(
        ConversationConfig {
            min_length: 3,
            max_length: 64,
            min_length_for_response: 5,
            ..Default::default()
          }
        ).unwrap();

    let mut conversation_manager = ConversationManager::new();

    let input_1 = "вот например вчера я думал, стоит ли заказать пиццу. Но иногда я себе говорю \"Блин, хватит жрать пиццу, есть же и другая еда, скушай там салатик или супчик, надоела пицца эта\" ну и я такой подумал. Надо монетку подбросить. Но у меня все монетки в копилке. Сейчас даже фото этой копилки найду. И я установил на телефон приложение, которое подбрасывают монетку. Вот. И я говорю себе. \"ну если выпадет решка - я заказываю пиццу, если орёл - заказываю супчик\" ну и я как бы уже не делаю это случайным, это ведь я выбрал, кто будет орлом, а кто решкой. По идее я должен был подкинуть монетку изначально на то, кто будет орлом, а кто будет решкой. Поэтому, наверное, это уже не была случайность. Тем не менее. Подбрасываю я такой эту монетку в телефоне, выпадает решка. И я расстраиваюсь, потому что я уже не хочу пиццу, я уже настроился на супчик, уже нашёл, где заказать хороший тай суп, поэтому я просто говорю себе \"нет, приложение херня, скачаю другое, это какое-то забагованное\", качаю другое, и там падает орёл. И я довольный заказываю себе суп и сырные палочки. И вот это ведь уже не случайность ? Я думаю, совсем не случайность. Тем не менее, я немного успокоил свою совесть и дал таким образом себе подумать над тем, а что я действительно хочу заказать ? И это вот такой банальный пример. Но можно ли вообще считать, что есть какая-то случайность ? Например ставлю я себе \"случайная раса\" в варкрафте и мне падают там 8 из 10 игр эльфы условные. Это  всё ещё случайность ? Или это уже поломанный скрипт ? Было бы ли правильно, если бы в \"случайности\" 3 раза из 12 игр падала каждая раса ? Я так не думаю, это уже не случайность, а статистика. Но я всё ещё верю, что любые случайности не очень случайны, хотя случаю стоит очень доверять, многие свои решения в жизни я сделал грубо говоря \"подбрасывая монетку\", и они оказались очень правильными. Хотя в конечном итоге не решка или орёл решали, буду ли я счастлив. Не так ли? Что ты думаешь по этому поводу?";
    let input_2 = "дорогая! У меня к тебе вопрос. Ты когда-то была в хвойном лесу? Знаешь, когда ты идёшь в лес, находишь хорошую такую берёзу, разбиваешь ей кору, вставляешь такую специальную штуку и там начинает по капельке капать бирюзовый сок. Ты на ночь оставляешь там банку, а в 5 утра тебя будит дедушка, вы идёте ранней осенью по заваленному листьями лесу, собираете грибочки в корзину, которую бабушка дала и так прохладно, в лесу ведь всегда холодно ? Ты пособирала эти грибочки час, устала и вы идёте к той берёзке, берёшь эту баночку, там ещё что-то попадало, какие-то листики, хвоя, маленькие веточки и делаешь такой глоток этого холодного берёзового сока и у тебя такое единение с природой, ты прям чувствуешь как будто дерево пьёшь, да ? Не то, что эти берёзовые соки в магазинах.. Химия сплошная, не передаёт совсем этот вкус природы и этот прекрасный настрой раннего осеннего леса с лёгкой усталостью. Это не заменит не красивая упаковка, не удобство обслуживания на кассе. Я правда никогда не пил берёзовый сок, да и дедушки у меня не было, и в лес я не люблю ходить. Но я об этом много слышал. И читал рассказы. Тот же Чехов. Как ты относишься к книгам Чехова ? Я знаю, что сейчас популярно считать, что он переоценен. Средний сатирик, Фёдор Михайлович намного лучше и всё вот это. Что ж, может и так, но может вся суть Чехова как раз и есть в этой детской простоте, наивности и хорошем выводе о прекрасных вещах, по типу классического \"В человеке должно быть всё прекрасно, и душа и тело, и одежда и мысли\" . Не уверен, что правильно эту цитату привёл, но в младшей школе классная руководительница постоянно говорила мне её, когда видела мои изрисованные в непонятно чём тетради и мой корявый почерк. Но что-то мы отходим от темы. Ты когда-то бывала в лесу ?";

    let translation_config =
      TranslationConfig::new(Language::RussianToEnglish, Device::cuda_if_available());

    let model = TranslationModel::new(translation_config).unwrap();

    let en_1 = model.translate(&[input_1]);
    let en_2 = model.translate(&[input_2]);

    assert!( !en_1.is_empty() );
    assert!( !en_2.is_empty() );

    let cache_slices = vec![en_1[0].as_str()];

    let encoded_history = conversation_model.encode_prompts(&cache_slices);

    let conv_id = conversation_manager.create(en_2[0].as_str());
    if let Some(cm) = conversation_manager.get(&conv_id) {
      cm.load_from_history(cache_slices, encoded_history);
    }

    let output = conversation_model.generate_responses(&mut conversation_manager);

    let out_values = output.values()
                            .cloned()
                            .map(str::to_string)
                            .collect::<Vec<String>>();

    assert!( !out_values.is_empty() )
  }
}
```

**Comment by guillaume-be** [comment]
Thank you, I could reproduce the issue and identified the root cause. This was caused by a hard-coded value of maximum length for the encoder input for encoder-decoder models of 1024. Since Marian models have a position embeddings matrix of size 512 this was causing an index out of bound error.

I just pushed some changes to the branch `long_translation_fix` that should resolve the issue and not cause a panic anymore.
Please note however:
- The input is effectively truncated to 512 input tokens, meaning part of the input is lost during translation. The pipeline does not support "windowed" translation as of now
- The Marian models have been trained on much shorter inputs than the one provided. Even though the pipeline should no longer panic, the quality of the translation will be poor for these inputs

Can you please try to check out this branch and let me know if it solves your issue?
```toml
[dependencies]
rust-bert = { git = "https://https://github.com/guillaume-be/rust-bert", branch = "long_translation_fix" }
```

**Comment by Qeenon** [comment]
@guillaume-be thank you, I will run test when I will be in mood for it, must be weekends or max Monday.

**Comment by Qeenon** [comment]
Tested, no fault anymore! but test I've posted here still fails because `out_values` is empty, guess it's not related and issue can be closed when this will be merged.

**Comment by guillaume-be** [comment]
I noticed too that for long inputs, the conversation model tends not to generate an answer (directly outputs `<EOS>`). This is probably due to the original dataset the model was trained on, and the model output quality can be expected to decrease the further you deviate from this original dataset distribution. 

The examples provided at https://github.com/microsoft/DialoGPT#generated-examples hint to shorter user inputs of 1-2 sentences (1000 tokens input starts to be closer to a monologue than a conversation)

**Comment by guillaume-be** [comment]
@Qeenon I will push a patch release tomorrow. Thank you again for raising this
